// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_OyVcCsokzE2QMUjgVLbKvyvRa29jok',
    appId: '1:425346138353:web:c9506d110e55e996b5a950',
    messagingSenderId: '425346138353',
    projectId: 'learn-firebase-635a5',
    authDomain: 'learn-firebase-635a5.firebaseapp.com',
    storageBucket: 'learn-firebase-635a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBI0tJMvhlIDZM1XoAAzI2aLNsNZVNEC0',
    appId: '1:425346138353:android:5aa51ecbfbf1ac4db5a950',
    messagingSenderId: '425346138353',
    projectId: 'learn-firebase-635a5',
    storageBucket: 'learn-firebase-635a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MyPw8N2cjYu9waYloGW1FXkQAkplswM',
    appId: '1:425346138353:ios:62b749156d5b36d3b5a950',
    messagingSenderId: '425346138353',
    projectId: 'learn-firebase-635a5',
    storageBucket: 'learn-firebase-635a5.appspot.com',
    iosBundleId: 'com.example.learnFirebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6MyPw8N2cjYu9waYloGW1FXkQAkplswM',
    appId: '1:425346138353:ios:62b749156d5b36d3b5a950',
    messagingSenderId: '425346138353',
    projectId: 'learn-firebase-635a5',
    storageBucket: 'learn-firebase-635a5.appspot.com',
    iosBundleId: 'com.example.learnFirebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_OyVcCsokzE2QMUjgVLbKvyvRa29jok',
    appId: '1:425346138353:web:19822b8706f59f1eb5a950',
    messagingSenderId: '425346138353',
    projectId: 'learn-firebase-635a5',
    authDomain: 'learn-firebase-635a5.firebaseapp.com',
    storageBucket: 'learn-firebase-635a5.appspot.com',
  );

}